<a href="https://colab.research.google.com/github/icarof98/Studies/blob/main/Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Air temperature example
This example shows how to train a geoRF regression model on data containing spatial features. In this example, the air temperature data is used.

In [17]:
!git clone https://github.com/margotgeerts/geoRF.git

Cloning into 'geoRF'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 6), reused 16 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (28/28), 26.73 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [18]:
%cd geoRF

/content/geoRF/geoRF/geoRF/geoRF/geoRF

In [19]:
!pip install -r requirements.txt

Collecting distgfs==1.1.0 (from -r requirements.txt (line 4))
  Using cached distgfs-1.1.0-py3-none-any.whl.metadata (3.5 kB)
Collecting geopandas==0.14.4 (from -r requirements.txt (line 5))
  Using cached geopandas-0.14.4-py3-none-any.whl.metadata (1.5 kB)
Collecting joblib==1.4.0 (from -r requirements.txt (line 6))
  Using cached joblib-1.4.0-py3-none-any.whl.metadata (5.4 kB)
Collecting kaggle==1.6.14 (from -r requirements.txt (line 7))
  Using cached kaggle-1.6.14-py3-none-any.whl
Collecting matplotlib==3.8.4 (from -r requirements.txt (line 8))
  Using cached matplotlib-3.8.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting numba==0.59.1 (from -r requirements.txt (line 9))
  Using cached numba-0.59.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting numpy==1.26.4 (from -r requirements.txt (line 10))
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pandas==2.2.1 (from -r requirements.txt (line 11))
  Using cached pandas-2.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting requests==2.32.3 (from -r requirements.txt (line 12))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting scikit-learn==1.4.2 (from -r requirements.txt (line 13))
  Using cached scikit_learn-1.4.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting scipy==1.13.0 (from -r requirements.txt (line 14))
  Using cached scipy-1.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting tqdm==4.66.4 (from -r requirements.txt (line 15))
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting urllib3==2.2.1 (from -r requirements.txt (line 16))
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting distwq>=1.1.0 (from distgfs==1.1.0->-r requirements.txt (line 4))
  Using cached distwq-1.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: dlib<20.0.0,>=19.24.0 in /usr/local/lib/python3.12/dist-packages (from distgfs==1.1.0->-r requirements.txt (line 4)) (19.24.6)
Requirement already satisfied: h5py<4.0.0,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from distgfs==1.1.0->-r requirements.txt (line 4)) (3.16.0)
Collecting mpi4py<4.0.0,>=3.1.3 (from distgfs==1.1.0->-r requirements.txt (line 4))
  Using cached mpi4py-3.1.6.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: fiona>=1.8.21 in /usr/local/lib/python3.12/dist-packages (from geopandas==0.14.4->-r requirements.txt (line 5)) (1.10.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas==0.14.4->-r requirements.txt (line 5)) (26.1)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from geopandas==0.14.4->-r requirements.txt (line 5)) (3.7.2)
Requirement already satisfied: shapely>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from geopandas==0.14.4->-r requirements.txt (line 5)) (2.1.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle==1.6.14->-r requirements.txt (line 7)) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.12/dist-packages (from kaggle==1.6.14->-r requirements.txt (line 7)) (2026.4.22)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle==1.6.14->-r requirements.txt (line 7)) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle==1.6.14->-r requirements.txt (line 7)) (8.0.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle==1.6.14->-r requirements.txt (line 7)) (6.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.8.4->-r requirements.txt (line 8)) (3.3.2)
Collecting llvmlite<0.43,>=0.42.0dev0 (from numba==0.59.1->-r requirements.txt (line 9))
  Using cached llvmlite-0.42.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.1->-r requirements.txt (line 11)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.1->-r requirements.txt (line 11)) (2026.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r requirements.txt (line 12)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r requirements.txt (line 12)) (3.13)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.4.2->-r requirements.txt (line 13)) (3.6.0)
INFO: pip is looking at multiple versions of distwq to determine which version is compatible with other requirements. This could take a while.
Collecting distwq>=1.1.0 (from distgfs==1.1.0->-r requirements.txt (line 4))
  Using cached distwq-1.2.0-py3-none-any.whl.metadata (7.8 kB)
  Using cached distwq-1.1.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from fiona>=1.8.21->geopandas==0.14.4->-r requirements.txt (line 5)) (26.1.0)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.12/dist-packages (from fiona>=1.8.21->geopandas==0.14.4->-r requirements.txt (line 5)) (8.3.3)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.12/dist-packages (from fiona>=1.8.21->geopandas==0.14.4->-r requirements.txt (line 5)) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from fiona>=1.8.21->geopandas==0.14.4->-r requirements.txt (line 5)) (0.7.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle==1.6.14->-r requirements.txt (line 7)) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle==1.6.14->-r requirements.txt (line 7)) (1.3)
Using cached distgfs-1.1.0-py3-none-any.whl (23 kB)
Using cached geopandas-0.14.4-py3-none-any.whl (1.1 MB)
Using cached joblib-1.4.0-py3-none-any.whl (301 kB)
Using cached matplotlib-3.8.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Using cached numba-0.59.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached pandas-2.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached scikit_learn-1.4.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Using cached scipy-1.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Using cached distwq-1.1.0-py3-none-any.whl (30 kB)
Using cached llvmlite-0.42.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.8 MB)
Building wheels for collected packages: mpi4py
  error: subprocess-exited-with-error

  × Building wheel for mpi4py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for mpi4py (pyproject.toml) ... error
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mpi4py)

In [20]:
import io
import requests
from urllib import request
import numpy as np
import pandas as pd
import geopandas as gpd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [44]:
# Get temperature data
# url = 'https://springernature.figshare.com/ndownloader/files/12609182'
# url_open = request.urlopen(url)
# df = pd.read_csv(io.StringIO(url_open.read().decode('utf-8')))

# Using the local file as suggested by the context
df = pd.read_csv('/content/stationDataAll.csv')

df = df[['Lat','Lon','meanT','meanP']]
df.rename(columns={"Lat":"y","Lon":"x"},inplace=True)
df

          y      x      meanT   meanP
0     36.83   7.82  18.025000   694.0
1     36.72   3.25  18.083333   672.0
2     36.72   5.07  17.366667   861.0
3     36.47   7.47  17.316667   554.0
4     36.28   6.62  15.425000   568.0
...     ...    ...        ...     ...
3071  54.65  -6.22   8.633333   961.0
3072  62.02  -6.77   6.225000  1423.0
3073  36.15  -5.35  17.441667   738.0
3074  32.63 -16.90  17.683333   612.0
3075  33.07 -16.35  18.508333   428.0

[3076 rows x 4 columns]

In [45]:

# Convert X-Y coordinates to a projected coordinate system
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.x, df.y, crs='EPSG:4326'))

gdf = gdf.to_crs('EPSG:3857')

df['x'] = gdf.geometry.x
df['y'] = gdf.geometry.y
df

                 y             x      meanT   meanP
0     4.415437e+06  8.705184e+05  18.025000   694.0
1     4.400150e+06  3.617883e+05  18.083333   672.0
2     4.400150e+06  5.643898e+05  17.366667   861.0
3     4.365487e+06  8.315566e+05  17.316667   554.0
4     4.339218e+06  7.369350e+05  15.425000   568.0
...            ...           ...        ...     ...
3071  7.294232e+06 -6.924072e+05   8.633333   961.0
3072  8.863887e+06 -7.536330e+05   6.225000  1423.0
3073  4.321281e+06 -5.955593e+05  17.441667   738.0
3074  3.846295e+06 -1.881299e+06  17.683333   612.0
3075  3.904599e+06 -1.820074e+06  18.508333   428.0

[3076 rows x 4 columns]

In [46]:

# Split data into train and test
data_train, data_test = train_test_split(df, test_size=0.3, shuffle=True, random_state=0)

# Scale the target value
scaler = MinMaxScaler()
data_train['meanT'] = scaler.fit_transform(data_train['meanT'].values.reshape(-1,1))
data_test['meanT'] = scaler.transform(data_test['meanT'].values.reshape(-1,1))

In [47]:
target = 'meanT'
X_train = data_train.drop([target], axis=1).values
y_train = data_train[target].values

X_test = data_test.drop([target], axis=1).values
y_test = data_test[target].values

In [48]:
# Check the X-Y coordinates (column indices are required for geoRF)
X_train[:,[0,1]]

array([[  5404732.35002346, -10386319.99804493],
       [  4964404.36013148, -11186896.37998292],
       [  4162440.73969107, -11026473.86180073],
       ...,
       [  5237970.70341953, -11431888.31532075],
       [ -4184284.27482761,  16414058.91746819],
       [  7156910.262561  ,   3075757.53061815]])

In [49]:
X_train.shape

(2153, 3)

In [ ]:
from geoRF import GeoRFRegressor

ModuleNotFoundError: No module named 'distgfs'

In [51]:
!pip install distgfs
from geoRF import GeoRFRegressor

Collecting distgfs
  Downloading distgfs-1.2.0-py3-none-any.whl.metadata (3.2 kB)
Collecting distwq>=1.1.0 (from distgfs)
  Using cached distwq-1.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: dlib>=19.24.0 in /usr/local/lib/python3.12/dist-packages (from distgfs) (19.24.6)
Requirement already satisfied: h5py>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from distgfs) (3.16.0)
Collecting mpi4py>=4.0.0 (from distgfs)
  Downloading mpi4py-4.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from distgfs) (2.0.2)
Requirement already satisfied: ruff>=0.6.9 in /usr/local/lib/python3.12/dist-packages (from distgfs) (0.15.11)
Downloading distgfs-1.2.0-py3-none-any.whl (23 kB)
Downloading distwq-1.2.1-py3-none-any.whl (31 kB)
Downloading mpi4py-4.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_5_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 21.6 MB/s eta 0:00:00
Installing collected packages: mpi4py, distwq, distgfs
Successfully installed distgfs-1.2.0 distwq-1.2.1 mpi4py-4.1.2

In [1]:
!pip install numpy==1.26.4 --force-reinstall
!pip install scikit-learn==1.4.2 --force-reinstall
georf_temp = GeoRFRegressor(n_estimators=100, max_features=None, n_jobs=-1, random_state=0)
georf_temp.fit(X_train,
               y_train,
               geo_features=[0,1], # X-Y column indices
               gens='da')  # Dual Annealing (DA) geospatial split generator

Collecting scikit-learn==1.4.2
  Using cached scikit_learn-1.4.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting numpy>=1.19.5 (from scikit-learn==1.4.2)
  Using cached numpy-2.4.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting scipy>=1.6.0 (from scikit-learn==1.4.2)
  Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.4.2)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn==1.4.2)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.4.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached numpy-2.4.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.6.0
    Uninstalling threadpoolctl-3.6.0:
      Successfully uninstalled threadpoolctl-3.6.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.5
    Uninstalling numpy-2.4.5:
      Successfully uninstalled numpy-2.4.5
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.3
    Uninstalling joblib-1.5.3:
      Successfully uninstalled joblib-1.5.3
  Attempting uninstall: scipy
    Found existing installation: scipy 1.17.1
    Uninstalling scipy-1.17.1:
      Successfully uninstalled scipy-1.17.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.4.2
    Uninstalling scikit-learn-1.4.2:
      Successfully uninstalled scikit-learn-1.4.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.4.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.4.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.5 which is incompatible.
Successfully installed joblib-1.5.3 numpy-2.4.5 scikit-learn-1.4.2 scipy-1.17.1 threadpoolctl-3.6.0

NameError: name 'GeoRFRegressor' is not defined

In [ ]:
from sklearn.metrics import mean_squared_error
print(f"train rmse: {mean_squared_error(y_train, georf_temp.predict(X_train), squared=False)}")
print(f"test rmse: {mean_squared_error(y_test, georf_temp.predict(X_test), squared=False)}")

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

train rmse: 0.014036317425465641
test rmse: 0.03631634852464978

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_temp = RandomForestRegressor(n_estimators=100, max_features=None, n_jobs=-1, random_state=0)
rf_temp.fit(X_train, y_train)

RandomForestRegressor(max_features=None, n_jobs=-1, random_state=0)

In [ ]:
print(f"train rmse: {mean_squared_error(y_train, rf_temp.predict(X_train), squared=False)}")
print(f"test rmse: {mean_squared_error(y_test, rf_temp.predict(X_test), squared=False)}")

train rmse: 0.015041919569707926
test rmse: 0.0405312127061455

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(